### ISSUE TITLE
Title PortableMineLauncher to MineLauncherPortable

### ISSUE THREAD

**Issue by Makazzz** [JarlPenguin/MinecraftLauncher2Portable#5]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Change Title to MineLauncherPortable

**Additional context**
This will keep the formality of PortableApps of [APPNAME]Portable and not PortableMineLauncher _Portable_

**Comment by Makazzz** [comment]
@JarlPenguin (sorry)

**Comment by JarlPenguin** [comment]
This means I'll have to update the AppID, and then another clean install will be required :/, my fault for not renaming it properly in the first place
